name: Node.js App Deployment

on:
  push:
    branches:
      - master # Defina a branch que você deseja acionar o fluxo

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 16
        cache: 'npm'
    - run: npm ci

    - name: executing remote ssh commands using password
      uses: appleboy/ssh-action@v0.1.8
      with:
        host: ${{ secrets.REMOTE_HOST }}
        username: ${{ secrets.REMOTE_USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        port: 22
        script: |
          sudo su
          curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.34.0/install.sh | bash
          . ~/.nvm/nvm.sh
          nvm install --lts
          node -e "console.log('Running Node.js ' + process.version)"
          nvm --version
          sudo yum install -y git
          git clone https://github.com/rodrigosousadf/simple-nodejs-app.git
          cd simple-nodejs-app/
          npm install -y
    - name: Start Node.js Application
      run: npm start &
    - name: Wait for Node.js Application to Finish
      run: |
        while ! nc -z localhost 3000; do
        sleep 1
        done
    - name: stop ec2 instance
      uses: flyweightrocks/aws-ec2-action@v1
      with:
        instance-id: 'Your Instance ID'
        wait-instance-running: true
        stop-instance: true

