name: Node.js App Deployment

on:
  push:
    branches:
      - main  # Defina a branch que você deseja acionar o fluxo

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 14  # Defina a versão do Node.js que você está usando

    - name: Install Dependencies
      run: npm install  # ou use yarn se estiver usando o Yarn

    - name: Build App
      run: npm start # Substitua pelo comando de construção do seu aplicativo

    - name: executing remote ssh commands using password
      uses: appleboy/ssh-action@v0.1.8
      with:
        host: ${{ secrets.REMOTE_HOST }}
        username: ${{ secrets.REMOTE_USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        port: 22
        script: |
          sudo su
          curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.34.0/install.sh | bash
          . ~/.nvm/nvm.sh
          nvm install node
          nvm --version
          yum install -y git
          git clone https://github.com/rodrigosousadf/simple-nodejs-app.git
          cd simple-nodejs-app
          npm install
          npm start start


  
